experiments = { ...
    'hrfpattern_1' ...
    'spatialpattern_1' ...
    'spatialpattern_2' ...
    'spatialpattern_3' ...
    'spatialpattern_4' ...
    }';

experimentList = table(experiments);

fname = 'experimentsToRun';
pth = vistadispRootPath;
writetable(experimentList, fullfile(pth, sprintf('%s.txt', fname)), ...
            'FileType','text', 'Delimiter', '\t', 'WriteVariableNames', false)
        
        
%fileId = fopen('experimentsToRun.txt', 'w')
%fprintf