

%         % Download spatiotemporal stimuli 
%         images = [];
%         for ii = 1:13 % why 13?
%             readPth = sprintf('https://wikis.nyu.edu/download/attachments/85394548/spatiotemporal%d.mat?api=v2', ii);
%             stimDir = fullfile(BAIRRootPath, 'stimuli');
%             fname = sprintf('spatiotemporal%d.mat', ii);
%             writePth = fullfile(stimDir, fname);
%             if ~exist(writePth, 'file'),  websave(writePth,readPth); end
%             tmp = load(writePth);
%             images = [images tmp.im];
%         end 


knk_idx = [...
            162 ... CRF-1
            164 ... CRF-2
            166 ... CRF-3
            167 ... CRF-4
            116 ... CRF-5
            150 ... GRATING
            154 ... PLAID
            158 ... CIRCULAR
            184 ... SPARSITY-1
            183 ... SPARSITY-2
            182 ... SPARSITY-3
            181 ... SPARSITY-4
            171 ... FACES-1
            171 ... FACES-2
            171 ... FACES-3
            171 ... FACES-4
            173 ... LETTERS-1
            173 ... LETTERS-2
            173 ... LETTERS-3
            173 ... LETTERS-4
            172 ... SCENES-1 (175??)
            172 ... SCENES-2 (175??)
            172 ... SCENES-3 (175??)
            172 ... SCENES-4 (175??)
            116 ... ONEPULSE-1
            116 ... ONEPULSE-2
            116 ... ONEPULSE-3
            116 ... ONEPULSE-4
            116 ... ONEPULSE-5
            116 ... ONEPULSE-6
            116 ... TWOPULSE-1
            116 ... TWOPULSE-2
            116 ... TWOPULSE-3
            116 ... TWOPULSE-4
            116 ... TWOPULSE-5
            116 ... TWOPULSE-6
            ];

        

        whichIm = {...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:2 ...
            3:4 ...
            5:6 ...
            7:8 ...
            1:2 ...
            3:4 ...
            5:6 ...
            7:8 ...
            1:2 ...
            3:4 ...
            5:6 ...
            7:8 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            1:6 ...
            };

        
        im_cell = images(knk_idx);
        
        images = [];
        for ii = 1:num_cats
            these_images = im_cell{ii}(:,:,whichIm{ii});
            images = cat(3, images, these_images);
        end